apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: achliopa/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  type: ClusterIP # default type can be ommitted
  selector:
    app: posts 
  ports: 
    - name: posts
      protocol: TCP
      port: 4000 # export the port our app to an external port
      targetPort: 4000 # internal port of pod (in code)