apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts ## find pods with this label to network
  ports: 
    - name: posts
      protocol: TCP
      port: 4000 # export the port our app to an external port
      targetPort: 4000 # internal port of pod (in code)
      